### ISSUE TITLE
Problem in jacobian method

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/matlab#1]
The jacobian(theta, ith) computes the jacobian until the joint ith. This method calls the raw_jacobian(theta, ith). However, this computes the x_effector until obj.links instead of ith  (line 282).  This returns a different Jacobian.

**Comment by bvadorno** [comment]
Hi, Juancho. I've just fixed it. Could you please test it?  Please let me know it works correctly now.

Cheers,
Bruno

**Comment by juanjqo** [comment]
Now it is working perfectly!
Thanks!
