### ISSUE TITLE
compatibility problem in the last version

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/matlab#10]
The last version of DQ robotics breaks my current codes. The attribute links() is not working. In the new version is called n_links(). This is a little change, but I think good idea to keep legacy methods or attributes.
I will update all my codes. But this problem probably will affect to many users.

Cheers,

Juancho

**Comment by bvadorno** [comment]
Hi, Juancho.

You don't need to update your codes right now. I'll implement a legacy method because it's much simpler than implementing a legacy attribute, assuming that you only read from `links` and don't need to directly write any information in it.

Cheers,
Bruno

**Comment by juanjqo** [comment]
Great!
Thanks!
