### ISSUE TITLE
Bug in plot function

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/matlab#16]
Hi @bvadorno 

There is a problem in plot function for DQ_kinematics objects in the last version. Sometimes, an undesired big black plane is plotted. 

I'm using Matlab R2016b on Ubuntu 18.04 LTS.

I attached a minimal example. Here is my code:

> clear all
> close all
> clc
> 
> 
> larm_DH_a      = [0,     0,     0.011,      0.1572]; %0.05
> larm_DH_alpha  = [pi/2, -pi/2, pi/2,   pi/2];
> larm_DH_d      = [0.0285,    0.0182,    0.1482, 0 ];
> larm_DH_theta  =  [pi/2,  0, pi/2,   pi/2  ];
> 
> larm_DH_matrix = [larm_DH_theta;
>                         larm_DH_d;
>                         larm_DH_a;
>                         larm_DH_alpha]; 
> 
> larm  = DQ_kinematics(larm_DH_matrix,  'standard');
> 
> base =  - 0.70711 - 0.70711*DQ.j + DQ.E*( - 0.0014142 + 0.20771*DQ.i + 0.0014142*DQ.j - 0.26181*DQ.k);
> base = normalize(base);
> 
> theta_larm =  [  1.570796326794897
>                1.570796326794897
>                                0
>               -1.570796326794897];
>           
> larm.set_base(base);
> plot(larm, theta_larm);
> view([-57 29])
> axis equal

Also, I attached two images in order to show the problem. I changed the black color and I used the green color (for the undesired plane) to show that the robot is plotted.

![Screenshot 2019-04-08 14:36:11](https://user-images.githubusercontent.com/23158313/55744739-fef32b00-5a0b-11e9-8111-f92dfc83011f.png)
![Screenshot 2019-04-08 14:37:03](https://user-images.githubusercontent.com/23158313/55744743-01558500-5a0c-11e9-9c14-d7179769fefb.png)

[plot_minimal_example.txt](https://github.com/dqrobotics/matlab/files/3055586/plot_minimal_example.txt)

**Comment by bvadorno** [comment]
Hi, Juancho.

I found the bug, but I'll push the fix in the next branch merge. For the moment, to prevent this problem you can just use a base frame such that the robot's first joint z-axis is not aligned with the world's x-axis.

Alternatively, if the former trick does not suit you, just change line 233 of DQ/plot.m from `v = DQ.j ` to `v = DQ.j*(plane_length/2); `

Cheers,
Bruno

**Comment by juanjqo** [comment]
Ok, thanks!

**Comment by bvadorno** [comment]
The fix is already available in the branch _mobile_base_.

**Comment by juanjqo** [comment]
@bvadorno 
 The method 'set_base' was removed?  (I'm using the mobile_base branch)

**Comment by bvadorno** [comment]
Yes for both questions. See https://github.com/dqrobotics/cpp/issues/9.

**Comment by bvadorno** [comment]
@juanjqo, the legacy function `set_base()` has been pushed to the _mobile_base_ branch.

Cheers,
Bruno

**Comment by juanjqo** [comment]
Great!

**Comment by juanjqo** [comment]
Bruno, using the last version of the _mobile_base_ branch, there is a problem yet.
Now, an undesired black line is plotted.
I'm using the same minimal example and the same computer.
![Screenshot 2019-04-09 09:28:49](https://user-images.githubusercontent.com/23158313/55800451-2a2c5780-5aaa-11e9-9da0-8ef14f2e7b6f.png)

Cheers, 

Juancho

**Comment by bvadorno** [comment]
Fixed in branch _mobile_base_.
