### ISSUE TITLE
Should DQ_WholeBody inherit from DQ_Kinematics?

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/matlab#25]
Hello, @bvadorno,

**Question**
Shouldn't `DQ_WholeBody` inherit from `DQ_Kinematics`?

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, @mmmarinho, 

Yes, it should. I'm currently improving this class to take into account reverse chains. I'll be pushing some nice modifications real soon and I'll update the class inheritance accordingly.

Cheers,
Bruno

**Comment by bvadorno** [comment]
All modifications were done. I also included an example of a two-legged robot, which uses reverse kinematic chains in the middle of the whole-body chain. The improved DQ_WholeBody works like a charm. 

Cheers,
Bruno
