### ISSUE TITLE
Distance_jacobians and residuals

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/matlab#26]
**Context**

In the same context of dqrobotics/cpp#15, a few comments regarding the MATLAB implementation

**Suggestions**

- [x] In `point_to_plane_residual` the `is_pure(point)` should probably be `is_pure_quaternion(point)`
- [x] In `point_to_plane_residual`, there is no check for `plane_derivative`. Something like `is_pure(P(plane_derivative))&&is_real(D(plane_derivative))` should work
- [x]  In `point_to_line_residual`, the `is_pure(workspace_line)` should probably be `is_line(workspace_line)`
- [x] In `point_to_line_distance_jacobian`  the `is_pure(workspace_line)` should probably be `is_line(workspace_line)`
- [x] In `plane_to_point_residual`, the checks should be added for both arguments.
- [x] In `plane_to_point_distance_jacobian`, the checks should be added for both arguments.

We might also considering adding those checks for the Jacobians unrelated to distance. What do you think?

**Comment by bvadorno** [comment]
Hi, @mmmarinho.

> We might also considering adding those checks for the Jacobians unrelated to distance. What do you think?

Yes, it is a good idea. 

Cheers,
Bruno
