### ISSUE TITLE
Problem running the cdts_bucket_kuka.m example

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/matlab#3]
Hi Bruno!

I tried to run the example cdts_bucket_kuka.m and I got the bellow error message:

> Error using DQ_kinematics/plot>plot_options (line 467)
> unknown option: nojaxes

> Error in DQ_kinematics/plot>dq_kinematics_plot (line 155)
>         opt = plot_options(robot, varargin);
> 
> Error in DQ_kinematics/plot (line 68)
>         dq_kinematics_plot(robot,q, varargin{:});
> 
> Error in cdts_bucket_kuka (line 39)
> plot(kuka1,initial_theta1',opt{:});

Thanks!

Cheers!

Juancho.

**Comment by bvadorno** [comment]
Fixed.
