### ISSUE TITLE
[BUG] rotation_angle is returning an imaginary value

### ISSUE THREAD

**Issue by maripaf** [dqrobotics/matlab#46]
**Bug description**
- When running a kinematic controller, after the system stabilizes with the error close to zero (1-invariant error), the rotation angle of the dual quaternion error is becoming imaginary.
If a dual quaternion has a unit norm, and the real part of the rotation is equal to 1, the rotation angle should be equal to zero. However, the function rotation_angle is returning an imaginary number.

**To Reproduce**
- Running the following code you will see that the running stops after 671 iterations, when the rotation angle becomes imaginary.

*Code*

```
% robot definition
kuka_dh_theta = [0, 0, 0, 0, 0, 0, 0];
kuka_dh_d = [0.3105, 0, 0.4, 0, 0.39, 0, 0];
kuka_dh_a = [0, 0, 0, 0, 0, 0, 0];
kuka_dh_alpha = [0, pi/2, -pi/2, -pi/2, pi/2, pi/2, -pi/2];
kuka_dh_matrix = [kuka_dh_theta;
                  kuka_dh_d;
                  kuka_dh_a;
                  kuka_dh_alpha]; 

kuka = DQ_SerialManipulator(kuka_dh_matrix,'modified');
    
% Initial conditions
q = [0 0.5 0 -1.2 0 0 0]';
dq = zeros(kuka.links, 1);
J = kuka.jacobian(q);
x = kuka.fkm(q);

% Desired configuration
q_desired = [0 0.5 0.5 -1.2 0 0 0]';
xd = kuka.fkm(q_desired);
         
i = 0;
T = 0.005;
k = 5;

while i < 2000
    
    i = i + 1;
    
    x = kuka.fkm(q);
    J = kuka.pose_jacobian(q);
   
    % invariant error
    x_til = x'*xd;
     
    % check rotation angle
    phi = rotation_angle(x_til);
    if ((imag(phi) ~= 0))
        fprintf('phi is not real')
        phi
        is_unit(x_til)
        Re(P(x_til))
        break;
    end
    
    % first order kinematic control
    N = haminus8(xd)*DQ.C8*J;
    dq = pinv(N)*(k*vec8(1-x_til));
    q = T*dq + q;
    u = q; 
        
    % error
    e = vec8(1 - x'*xd);
    norm(e)   
end

```
*Output*
```
phi = 0.0000e+00 + 4.2147e-08i
```

**Expected behavior**
- Since the dual quaternion has a unit norm, and Re(P(x_til)) is equal to one, I expected the rotation angle to be zero.

*Expected output*
```
phi = 0.0000e+00
```

**Environment:**
 - OS: Ubuntu 16.04
 - dqrobotics version: latest MATLAB version of 11 Set 2019
 - MATLAB version 2016b

**Additional context**
- This problem does not affect the classic kinematic control, but it affects anything that uses rotation, as the logarithm for example. A similar problem occurs in C++ version.

**Comment by bvadorno** [comment]
@maripaf Thanks a lot for opening this issue. I only suggest that, when facing similar problems, you present a minimum example related to the issue itself. Since the problem has nothing to do with kinematic control and is related only to the method `rotation_angle`, a cleaner example would be something like 

```
a = DQ(1.000000000000001)
norm(a)
>> 1
a.rotation_angle
>> 0.0000e+00 + 4.7122e-08i
```

Cheers, 
Bruno
