### ISSUE TITLE
[REQUEST]  Add set_damping to DQ_ClassicQPController. 

### ISSUE THREAD

**Issue by StUrb** [dqrobotics/matlab#47]
**Request description**
- I am currently using the class DQ_ClassicQPController and I need to change the damping factor in order to test my controller. But this class does not have a set_damping method. Is it possible to add this method? 

*Code*
It would be something like:

function set_damping(controller,damping)
        controller.damping = damping;
end

**Comment by bvadorno** [comment]
Hi @StUrb,

Actually, it does. Since `DQ_ClassicQPController` is a subclass of `DQ_KinematicController`, which implements the method `set_damping`, then `DQ_ClassicQPController` has it too. 

Bruno
