### ISSUE TITLE
[REQUEST] Abstract classes for robots in V-REP

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/matlab#48]
Since each robot joint in V-REP is associated with a name, it is convenient to encapsulate this information inside the robot class. In addition, classes implementing robots that use the V-REP interface should be a subclass of the abstract class `DQ_VrepRobot` to provide the methods `get_arm_joint_names`, `send_q_to_vrep`, and `get_q_from_vrep`.

Another important thing is to not use static methods for `send_q_to_vrep` and `get_q_from_vrep` because this forces the programmer to hard code the V-REP robot name inside the method. In my opinion, a better idea would be to define a variable `robot_name` that stores the V-REP robot name, which would be determined when instantiating an object (i.e., the name would be passed to the class constructor).

**Comment by mmmarinho** [comment]
Hello, @bvadorno 

Implemented on the private repository for review.
