### ISSUE TITLE
[QUESTION] Support for dummy joints?

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/matlab#50]
Hello, @bvadorno,

I remember we discussed about dropping support for dummy joints in `DQ_SerialManipulator`, but it seems that they are still alive in release 19.10.0.

Are we planning on removing them soon?

**Comment by bvadorno** [comment]
Hello, @mmmarinho. 

Yes, we are. As soon as we finish our tutorial paper, we can think about those things. Also, I think it's time to build a roadmap to guide our next steps. What do you think?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, @bvadorno,

I think that's a good idea.
(We talked about this before in a meeting but forgot to reply on github)

Cheers,
Murilo

**Comment by bvadorno** [comment]
Hello, @mmmarinho, 

I removed the support for dummy joints in my [development branch](https://github.com/dqrobotics/matlab/tree/updating_to_20_04_bva). Since I'll be doing a pull request soon, I'll close this issue.

Cheers,
Bruno
